import type { Video } from './types';

export const videos: Video[] = [
  {
    id: '1',
    title: 'Panetone perfeito - Kinder Bueno',
    description: 'Aprenda o passo a passo para fazer um panetone perfeito, fofinho e delicioso com esta receita incrível.',
    youtubeId: '_wmQZbY0U0M',
    imageId: 'panettone-1',
    isPremium: false,
  },
  {
    id: '2',
    title: 'Panetone perfeito - Brigadeiro e KITKAT',
    description: 'Uma receita premium de panetone de Brigadeiro E KITKAT que vai impressionar a todos. Perfeito para uma ocasião especial.',
    youtubeId: '0qwydyeHoMs',
    imageId: 'panettone-2',
    isPremium: true,
  },
  {
    id: '3',
    title: 'Panetone perfeito - Bolo De Cenoura',
    description: "O sabor irresistível e cremoso do bolo de cenoura agora em um delicioso panetone gourmet.",
    youtubeId: 'WfwLlODzfRA',
    imageId: 'panettone-3',
    isPremium: false,
  },
  {
    id: '4',
    title: 'Panetone perfeito - Segunda Receita de Bolo de De Cenoura',
    description: 'Explore a rica história deste icônico pão doce italiano. Um documentário premium para os amantes da gastronomia.',
    youtubeId: 'mEy6uF4hA-Q',
    imageId: 'panettone-4',
    isPremium: true,
  },
  {
    id: '5',
    title: 'Panetone perfeito - Ninho Com Nutela',
    description: 'Uma combinação irresistível de leite em pó Ninho e creme de avelã Nutella, perfeita para os amantes de doces.',
    youtubeId: 'VbTf4NtkCc0',
    imageId: 'panettone-5',
    isPremium: false,
  },
  {
    id: '6',
    title: 'Panetone Perfeito - Brigadeiro De Pistache',
    description: 'Um sabor sofisticado e delicioso que vai te surpreender. Receita premium exclusiva.',
    youtubeId: 'YZ4z_MRVog0',
    imageId: 'panettone-6',
    isPremium: true,
  },
  {
    id: '7',
    title: 'Brownietone - Mini Panetone gourmet',
    description: 'A união perfeita entre brownie e panetone. Uma explosão de sabor para os chocólatras.',
    youtubeId: 'BID3AE6eTvs',
    imageId: 'panettone-7',
    isPremium: false,
  },
  {
    id: '8',
    title: 'Panetone Perfeito - Beijinho',
    description: 'Quem resiste a um delicioso beijinho? Agora imagine essa delícia em um panetone super macio.',
    youtubeId: 'IvDRkdF9irU',
    imageId: 'panettone-8',
    isPremium: true,
  },
];
