import type { Video } from './types';

export const videos: Video[] = [
  {
    id: '1',
    title: 'Panetone perfeito - Kinder Bueno',
    description: 'Aprenda o passo a passo para fazer um panetone perfeito, fofinho e delicioso com esta receita incrível.',
    youtubeId: '_wmQZbY0U0M',
    imageId: 'panettone-1',
    isPremium: false,
  },
  {
    id: '2',
    title: 'Panetone perfeito - Brigadeiro e KITKAT',
    description: 'Uma receita premium de panetone de Ferrero Rocher que vai impressionar a todos. Perfeito para uma ocasião especial.',
    youtubeId: '0qwydyeHoMs',
    imageId: 'panettone-2',
    isPremium: true,
  },
  {
    id: '3',
    title: 'Panetone perfeito - Bolo De Cenoura',
    description: "Não tem tempo para um panetone de tamanho normal? Estas mini versões são rápidas, fáceis e igualmente deliciosas.",
    youtubeId: 'WfwLlODzfRA',
    imageId: 'panettone-3',
    isPremium: false,
  },
  {
    id: '4',
    title: 'Panetone perfeito - Segunda Receita de Bolo de De Cenoura',
    description: 'Explore a rica história deste icônico pão doce italiano. Um documentário premium para os amantes da gastronomia.',
    youtubeId: 'mEy6uF4hA-Q',
    imageId: 'panettone-4',
    isPremium: true,
  },
  {
    id: '5',
    title: 'Panetone Red Velvet com Cream Cheese',
    description: 'Uma versão moderna e irresistível do clássico panetone, com a cor e o sabor inconfundíveis do Red Velvet.',
    youtubeId: 'qS0E0f_v-6s',
    imageId: 'panettone-5',
    isPremium: false,
  },
  {
    id: '6',
    title: 'Panetone de Limão Siciliano (Premium)',
    description: 'Um sabor cítrico e refrescante que vai te surpreender. Receita premium exclusiva.',
    youtubeId: 'z-T6N_V2yqg',
    imageId: 'panettone-6',
    isPremium: true,
  },
  {
    id: '7',
    title: 'Chocotone Vulcão de Nutella',
    description: 'Para os amantes de chocolate, um chocotone com recheio cremoso e irresistível de Nutella.',
    youtubeId: '3GZtFmF-p0c',
    imageId: 'panettone-7',
    isPremium: false,
  },
  {
    id: '8',
    title: 'Panetone Salgado: Calabresa com Queijo',
    description: 'Quem disse que panetone precisa ser doce? Experimente esta deliciosa versão salgada.',
    youtubeId: 'k4q8k2v_o_c',
    imageId: 'panettone-8',
    isPremium: true,
  },
];
